# Generated by Django 4.2.13 on 2024-05-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.CharField(max_length=100, verbose_name='Precio')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
        ),
    ]
