# Generated by Django 4.2.13 on 2024-06-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_pedido_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('dni', models.CharField(max_length=100, verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.client', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.FloatField(max_length=100, verbose_name='Precio')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='web.product', verbose_name='Productos'),
        ),
    ]
