# Generated by Django 4.2.13 on 2024-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_client_order_product_delete_cliente_delete_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MAIN', 'Principal'), ('SIDE', 'Acompañamiento'), ('DESRT', 'Principal'), ('SALAD', 'Ensalada'), ('DRINK', 'Bebida')], max_length=5, verbose_name='Categoría'),
        ),
    ]
