# Generated by Django 4.2.13 on 2024-05-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('dni', models.CharField(max_length=100, verbose_name='DNI')),
            ],
        ),
    ]
